### ISSUE TITLE
request end

### ISSUE THREAD

**Issue by Devhercule** [joeferner/node-http-mitm-proxy#143]

**Comment by Devhercule** [comment]
that can be solved by adding this code :

```
ctx.clientToProxyRequest.connection.on('close', function() {
			ctx.proxyToServerRequest.abort();
		});
```

This solve the probleme, but it provides other errors, like :

```
PROXY_TO_SERVER_REQUEST_ERROR: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12) code: 'ECONNRESET' }
```

Is there a better solution?

**Comment by Devhercule** [comment]
The problem is that the `node-http-mitm-proxy` don't automatically close  `proxyToServerRequest ` when `clientToProxyRequest ` is closed.
