### ISSUE TITLE
error in package while running google example TypeError: callback is not a function

### ISSUE THREAD

**Issue by SantoshSrinivas79** [joeferner/node-http-mitm-proxy#212]
I'm running [this google example](https://github.com/joeferner/node-http-mitm-proxy/blob/master/examples/modifyGoogle.js) and getting the following error:

```sh
listening on 8081
/Users/santosh/trial/node_modules/http-mitm-proxy/lib/proxy.js:97
        callback();
        ^

TypeError: callback is not a function
    at Server.self.httpServer.listen (/Users/santosh/trial/node_modules/http-mitm-proxy/lib/proxy.js:97:9)
    at Object.onceWrapper (events.js:277:13)
    at Server.emit (events.js:194:15)
    at emitListeningNT (net.js:1311:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I'm running node `v10.15.1`

**Comment by AleshaOleg** [comment]
https://github.com/joeferner/node-http-mitm-proxy/pull/206
