### ISSUE TITLE
Error while using http-mitm-proxy.

### ISSUE THREAD

**Issue by shark-S** [joeferner/node-http-mitm-proxy#87]
I got this error when i am trying to use "http-mitm-proxy".

/home/shark_s/node_modules/http-mitm-proxy/lib/middleware/wildcard.js:8
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shark_s/node_modules/http-mitm-proxy/lib/proxy.js:24:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by switer** [comment]
What's your node version ? 

```
node --version
```

**Comment by shark-S** [comment]
v0.10.25

**Comment by shark-S** [comment]
Yeah i got it. Its nodejs version problem i have to use "nodejs --harmony test.js" to run this.
